kind: pipeline
type: docker
name: default

steps:
- name: Build & publish  
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password: 
      from_secret: DOCKER_PASSWORD
    repo:  
      from_secret: IMAGE_NAME
    tags: latest
    dry_run: false
  when:
    branch:
    - master
- name: Deploy
  image: handspiker2/ci-tools:latest
  environment:
    SSH_PRIVATE: $SSH_PRIVATE
    IMAGE_NAME: $IMAGE_NAME
    DEPLOY_HOST: $DEPLOY_HOST
    DEPLOY_USER: $DEPLOY_USER
    CONTAINER_NAME: $CONTAINER_NAME

  commands:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - touch ~/.ssh/known_hosts
    - ssh-keyscan -H $${DEPLOY_HOST} >> ~/.ssh/known_hosts
    - echo "$$SSH_PRIVATE" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
    - run_command='docker run -td --restart unless-stopped --network proxy -l traefik.frontend.entryPoints=https,http -l traefik.enable=true -l traefik.frontend.rule="Host:clinic-map.spikedhand.com" -l traefik.docker.network=proxy -v /apps/covid-map/location_cache.json:/app/location_cache.json -v /apps/covid-map/www/appointments.json:/app/www/appointments.json'
    - |
        cat <<EOF | ssh $${DEPLOY_USER}@$${DEPLOY_HOST}
        docker pull ${IMAGE_NAME}
        $$run_command --name temp_$${CONTAINER_NAME} $${IMAGE_NAME}
        ( docker stop $${CONTAINER_NAME} && docker rm $${CONTAINER_NAME} ) || true
        $$run_command --name $${CONTAINER_NAME} $${IMAGE_NAME}
        ( docker stop temp_$${CONTAINER_NAME} && docker rm temp_$${CONTAINER_NAME} ) || true